### ISSUE TITLE
特例祝日の処理がありません

### ISSUE THREAD

**Issue by sozik** [suzunone/JapaneseDate#24]
下記のWEBの祝日と比べたら、2019／10／22の祝日がないということが発見しました。
https://holidays-calendar.net/calendar/japan_calendar.html

他のレポジトリのソース見て、一部の特例とかあります。
例えば、
2020: 国民の祝日に関する法律の一部を改正する法律(平成30年法律第57号)
2019: 天皇の即位の日及び即位礼正殿の儀の行われる日を休日とする法律
2020: 国民の祝日に関する法律(昭和23年法律第178号)の特例
など
下記のソースの祝日が正しいかどうかわからないですが、せめて2019／10／22の祝日があります。ご参照ください。
https://github.com/Lalcs/jpholiday/blob/master/jpholiday/jpholiday.py

**Comment by suzunone** [comment]
ご報告ありがとうございます。
対応しました。
v5.3以降を使用してください。
